/** AI tutor powered by Mistral. Calls a server proxy so the API key never ships to the browser. */
import { z } from "zod";

export interface MistralConfig { apiKey: string; model?: string }

export type PlanRequest = {
  /** English words the learner wants to study (from the 5,000-word library). */
  words: { w: string; th: string; pos: string }[];
  /** Minutes per day the learner can commit. */
  minutesPerDay: number;
  /** Learner's self-reported level. */
  level: "beginner" | "intermediate" | "advanced";
  /** Optional custom goal, e.g. "เตรียมสอบ TOEIC" or "อยากพูดกับชาวต่างชาติได้". */
  goal?: string;
};

const MistralResponseSchema = z.object({
  choices: z.array(z.object({ message: z.object({ content: z.string() }) })),
});

/** Proxy request shape shared with the server route /api/mistral/chat. */
const proxyPayload = (messages: { role: string; content: string }[], config: MistralConfig) => ({
  messages,
  model: config.model ?? "mistral-large-latest",
  maxTokens: 2000,
});

async function chat(messages: { role: string; content: string }[], config: MistralConfig): Promise<string> {
  // Vite dev server proxies /api to the Express server via the same origin.
  const resp = await fetch("/api/mistral/chat", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ ...proxyPayload(messages, config), apiKey: config.apiKey }),
  });
  if (!resp.ok) {
    const text = await resp.text().catch(() => "");
    throw new Error(text || `Mistral request failed (${resp.status})`);
  }
  const json = await resp.json();
  return MistralResponseSchema.parse(json).choices[0]?.message?.content ?? "";
}

export function buildStudyPlan(request: PlanRequest, config: MistralConfig): Promise<string> {
  const wordList = request.words.map((word) => `${word.w} (${word.pos}) — ${word.th}`).join("\n");
  const system = `You are a friendly English learning coach for Thai learners. Respond in Thai, except English example sentences.
Given a word list, daily minutes, and level, return a Markdown study plan:
- **ภาพรวมแผน** — short summary tailored to the goal.
- **แผนรายสัปดาห์ (4 สัปดาห์)** — 2–4 bullet points per week showing which words/phases to focus on.
- **ตารางทบทวนรายวัน** — a Markdown table: | วันที่ | คำศัพท์ที่ศึกษา | กิจกรรม | เวลา | — split the words across days to fit the daily minutes.
- **เทคนิคการจำ** — 3 practical SRS-friendly tips in Thai.
- **ประโยคตัวอย่าง** — 5 example sentences (English + Thai translation) using words from the list.
Keep it encouraging, concrete, and under 1,200 words.`;
  const user = `ระดับ: ${request.level}
เวลาที่มีต่อวัน: ${request.minutesPerDay} นาที
${request.goal ? `เป้าหมาย: ${request.goal}` : "เป้าหมาย: เรียนรู้คำศัพท์ใหม่ให้จำได้ระยะยาว"}

คำศัพท์ที่เลือก (คำ – ประเภท – ความหมายไทย):
${wordList}

ช่วยจัดทำแผนการเรียนตามข้อกำหนดด้านบน`;
  return chat(
    [
      { role: "system", content: system },
      { role: "user", content: user },
    ],
    config,
  );
}

export function askTutor(question: string, recentWords: { w: string; th: string }[], config: MistralConfig): Promise<string> {
  const wordsCtx = recentWords.length
    ? `คำศัพท์ที่ผู้เรียนกำลังศึกษา: ${recentWords.map((w) => `${w.w} — ${w.th}`).join(", ")}`
    : "";
  return chat(
    [
      { role: "system", content: `You are a patient English tutor for a Thai learner. Explain in Thai with short English examples. Keep answers under 300 words. If the question touches words the learner studies, tie the explanation to them. ${wordsCtx}` },
      { role: "user", content: question },
    ],
    config,
  );
}

/** Level labels used for placement recommendations. */
export type ProficiencyLevel = "beginner" | "elementary" | "intermediate";

/** Placement test: 10 multiple-choice questions generated by Mistral, returned as JSON. */
export async function generatePlacementTest(config: MistralConfig): Promise<{ questions: { en: string; thQuestion: string; choices: string[]; correct: number; explain: string }[] }> {
  const system = `You create English placement test questions for Thai learners who are beginners.
Return ONLY a JSON object with a single key "questions" containing an array of exactly 10 objects. Each object:
{
  "en": "A short, very simple English sentence with one blank (____) testing basic vocabulary or grammar (articles, to be verbs, present simple, basic prepositions, common daily-life words).",
  "thQuestion": "Thai translation of the sentence with instructions like เลือกคำตอบที่ถูกต้อง",
  "choices": ["a", "b", "c", "d"],
  "correct": 0,
  "explain": "Short Thai explanation of the correct answer"
}
Difficulty must progress from very easy (questions 1-3) to easy-basic (4-7) to slightly challenging beginner (8-10). Choices must be 4 short options in lowercase. Keep questions practical: daily life, family, food, time, work.`;
  const answer = await chat(
    [{ role: "system", content: system }, { role: "user", content: "สร้างแบบทดสอบวัดระดับภาษาอังกฤษเบื้องต้น 10 ข้อ" }],
    config,
  );
  const fenced = answer.match(/```(?:json)?[\s\S]*?\{[\s\S]*?\}[\s\S]*?```/);
  const match = answer.match(/\{[\s\S]*\"questions\"[\s\S]*\}/);
  const candidate = fenced ? fenced[0].replace(/```(?:json)?|```/g, "").trim() : match ? match[0] : null;
  if (!candidate) throw new Error("AI ส่งคำตอบรูปแบบผิดปกติ ลองใหม่อีกครั้ง");
  let parsed: { questions?: unknown };
  try {
    parsed = JSON.parse(candidate);
  } catch {
    const arrayMatch = answer.match(/\[[\s\S]*\]/);
    if (!arrayMatch) throw new Error("AI ส่งคำตอบรูปแบบผิดปกติ ลองใหม่อีกครั้ง");
    parsed = { questions: JSON.parse(arrayMatch[0]) };
  }
  const raw = parsed.questions;
  if (!Array.isArray(raw) || raw.length === 0) throw new Error("AI ส่งคำตอบรูปแบบผิดปกติ ลองใหม่อีกครั้ง");
  const items = raw.slice(0, 10).map((q: { en?: string; thQuestion?: string; choices?: string[]; correct?: number; explain?: string }) => ({
    en: q.en || "",
    thQuestion: q.thQuestion || "เลือกคำตอบที่ถูกต้อง",
    choices: Array.isArray(q.choices) ? q.choices.slice(0, 4) : [],
    correct: typeof q.correct === "number" ? Math.max(0, Math.min(3, q.correct)) : 0,
    explain: q.explain || "",
  }));
  return { questions: items };
}

/** Interpret a placement test score into a level recommendation. */
export function interpretScore(correct: number, total: number): { level: ProficiencyLevel; title: string; advice: string } {
  const pct = total > 0 ? correct / total : 0;
  if (pct >= 0.8) return { level: "intermediate", title: "ระดับกลาง", advice: "คุณพื้นฐานแน่นแล้ว ระบบจะแนะนำคำศัพท์ระดับใช้งานจริงและประโยคที่ยาวขึ้น ลองตั้งเป้าหมายเป็น TOEIC หรือการพูดคุยกับชาวต่างชาติ" };
  if (pct >= 0.5) return { level: "elementary", title: "ระดับเริ่มต้น", advice: "คุณเริ่มจำพื้นฐานได้แล้ว ระบบจะเน้นคำศัพท์ที่ใช้บ่อยที่สุดในชีวิตประจำวันและประโยคสั้น ๆ สม่ำเสมอวันละ 10–15 นาทีจะเห็นผลเร็ว" };
  return { level: "beginner", title: "ระดับเริ่มต้นจากศูนย์", advice: "ไม่ต้องกังวล — ใครก็เริ่มจากจุดนี้ได้ ระบบจะปูตั้งแต่คำศัพท์พื้นฐานที่สุด ฟังเสียง พูดตาม และทบทวนทีละน้อยทุกวัน" };
}

/** Build a 7-day auto study plan tailored to the placement level. */
export function buildSevenDayPlan(config: MistralConfig, level: ProficiencyLevel, words: { w: string; th: string; pos: string }[]): Promise<string> {
  const wordList = words.map((w) => `${w.w} (${w.pos}) — ${w.th}`).join("\n");
  const system = `You are an encouraging English coach for Thai learners. Respond in Thai, keep English in short examples.
Given the learner's level and a word list, produce a concrete 7-day plan in Markdown:
- **แผน 7 วันของคุณ** — one short intro line matching their level (use simpler language for beginner/elementary).
- A Markdown table: | วันที่ | คำศัพท์ | กิจกรรม | เวลา | — exactly 7 rows, splitting the words across the 7 days (roughly equal per day). Day 1 starts with listening and shadowing, days 2–4 mix new words with review, days 5–6 add sentence practice, day 7 is a self-test review of all words.
- **กฎ 3 ข้อสำหรับสัปดาห์แรก** — three ultra-simple rules (e.g. เรียนไม่เกิน 15 นาที, ทบทวนคำเก่าก่อนคำใหม่เสมอ, ออกเสียงดังทุกคำ).
- **ประโยคเริ่มต้น** — 4 short example sentences using words from the list (English + Thai).
Keep total under 800 words.`;
  return chat(
    [{ role: "system", content: system }, { role: "user", content: `ระดับ: ${level}\n\nคำศัพท์:\n${wordList || "(ยังไม่เลือกคำ — ใช้คำศัพท์พื้นฐานที่พบบ่อยสุด)"}` }],
    config,
  );
}

/** Scenario lesson: a short role-play dialogue generated by Mistral for a real-life situation. */
export function buildScenarioLesson(config: MistralConfig, situation: string, level: ProficiencyLevel): Promise<string> {
  const system = `You teach practical English to Thai beginners through real-life mini role-plays. Respond in Thai with English dialogue lines.
For the given situation, produce:
- **สถานการณ์: <situation>** — one sentence setting the scene in Thai.
- **บทสนทนา** — 6 short exchange pairs (A/B), each with the English line followed by its Thai translation in parentheses. Use very simple words suitable for the level.
- **คำที่ควรจำ** — a Markdown table: | คำ | ความหมาย | ตัวอย่าง | — 5 key words/phrases from the dialogue (English word, Thai meaning, a short example sentence).
- **ลองที่นี้** — 3 practice prompts in Thai asking the learner to try saying something in the situation.
Keep total under 600 words.`;
  return chat(
    [{ role: "system", content: system }, { role: "user", content: `สถานการณ์: ${situation}\nระดับ: ${level}` }],
    config,
  );
}

/** Correct a learner's English sentence with friendly feedback. */
export function correctSentence(config: MistralConfig, sentence: string, recentWords: { w: string; th: string }[]): Promise<string> {
  const wordsCtx = recentWords.length ? `คำที่ผู้เรียนกำลังศึกษา: ${recentWords.map((w) => `${w.w} — ${w.th}`).join(", ")}` : "";
  const system = `You are a kind English writing coach for Thai learners. The learner writes an English sentence. Respond in Thai:
1. **ผ่านเลย** or **ใกล้แล้ว** or **ลองอีกที** — one-line verdict (green if correct, amber if close, red if confusing).
2. **ประโยคที่ปรับแล้ว** — the corrected sentence in English. If the original was already correct, say so and praise.
3. **ทำไม** — one or two short Thai sentences explaining the change (grammar, word order, preposition). Keep explanations extremely simple.
4. **ประโยคอื่นที่ใช้ได้** — one alternative sentence.
Keep the whole reply under 150 words. ${wordsCtx}`;
  return chat(
    [{ role: "system", content: system }, { role: "user", content: sentence || "—" }],
    config,
  );
}
