/** Study Ledger design: calm editorial dashboard; ivory, ink navy and Memorise Green guide every learning action. */
import { useEffect, useMemo, useState } from "react";
import { ArrowUpRight, BookOpen, Check, ChevronRight, Clock3, Flame, Layers3, LibraryBig, RotateCcw, Search, Sparkles, Target, X } from "lucide-react";
import { AiTutor } from "@/components/AiTutor";
import { LearningHub } from "@/components/LearningHub";
import { ChatPractice } from "@/components/ChatPractice";
import { DailyStarter } from "@/components/DailyStarter";
import { ListeningDrill } from "@/components/ListeningDrill";
import { ReviewGames } from "@/components/ReviewGames";
import PlacementTest from "@/components/PlacementTest";
import { ScenarioLab, SentenceGym } from "@/components/ScenarioLab";
import { toast } from "sonner";
import { useVocabulary, type VocabularyWord } from "@/hooks/useVocabulary";
import { computeStreak, gradeLabel, isDue, lastSevenDays, logTodayReview, nextIntervalLabel, readDailyLog, reviewWord, setDailyGoal, type Grade, type SrsStore } from "@/lib/srs";

type View = "today" | "library" | "insights";
const STORE_KEY = "englishvocab-srs-store-v1";
const SAVED_KEY = "englishvocab-srs-saved-v1";
const asset = {
  hero: "/manus-storage/englishvocab-study-ledger-hero_6c5b274e.jpg",
  garden: "/manus-storage/englishvocab-memory-garden_31ff2754.jpg",
  progress: "/manus-storage/englishvocab-progress-sunrise_818cae57.jpg",
  logo: "/manus-storage/englishvocab-logo_37eeae11.png",
};
const keyOf = (word: VocabularyWord) => word.w.toLowerCase();
function stored<T>(key: string, fallback: T): T { try { return JSON.parse(localStorage.getItem(key) || "") as T; } catch { return fallback; } }
function thaiDate() { return new Intl.DateTimeFormat("th-TH", { weekday: "long", day: "numeric", month: "long" }).format(new Date()); }

function Header({ onReview }: { onReview: () => void }) {
  return <header className="topbar"><a className="brand" href="#today"><span className="brand-mark"><img src={asset.logo} alt="" /><i /><b /></span><span>EnglishVocab <em>SRS</em></span></a><div className="topbar-actions"><span>จำได้ดีขึ้นทีละคำ</span><button className="icon-button" title="เริ่มทบทวน" onClick={onReview}><Sparkles size={17} /></button></div></header>;
}
function Sidebar({ view, setView, due }: { view: View; setView: (value: View) => void; due: number }) {
  const items = [["today", "วันนี้", BookOpen], ["library", "คลังคำศัพท์", LibraryBig], ["insights", "ความคืบหน้า", Target]] as const;
  return <aside className="sidebar"><p className="sidebar-label">STUDY LEDGER</p><nav>{items.map(([id, label, Icon]) => <button key={id} className={`nav-item ${id === view ? "active" : ""}`} onClick={() => setView(id)}><Icon size={18} /><span>{label}</span>{id === "today" && due > 0 ? <b>{due}</b> : null}</button>)}</nav><div className="sidebar-bottom"><div className="streak-mini"><Flame size={18} /><div><strong>ทุกวันมีค่า</strong><span>บันทึกเรียนส่วนตัว</span></div></div><p>ความคืบหน้าทั้งหมดเก็บอยู่ในเบราว์เซอร์ของคุณ</p></div></aside>;
}
function Ring({ value }: { value: number }) {
  const circumference = 263.9;
  return <div className="progress-ring"><svg viewBox="0 0 100 100"><circle className="ring-track" cx="50" cy="50" r="42" /><circle className="ring-value" cx="50" cy="50" r="42" style={{ strokeDasharray: circumference, strokeDashoffset: circumference - circumference * value / 100 }} /></svg><strong>{value}%</strong></div>;
}
function StudySession({ queue, store, onGrade, close }: { queue: VocabularyWord[]; store: SrsStore; onGrade: (word: VocabularyWord, grade: Grade) => void; close: () => void }) {
  const [index, setIndex] = useState(0); const [revealed, setRevealed] = useState(false); const [done, setDone] = useState(false); const current = queue[index];
  const grade = (value: Grade) => { if (!current) return; onGrade(current, value); if (index + 1 === queue.length) setDone(true); else { setIndex(index + 1); setRevealed(false); } };
  useEffect(() => { const listen = (event: KeyboardEvent) => { if (event.key === "Escape") close(); if (event.key === " " || event.key === "Enter") { event.preventDefault(); setRevealed(true); } const map: Record<string, Grade> = { "1": "again", "2": "hard", "3": "good", "4": "easy" }; if (revealed && map[event.key]) grade(map[event.key]); }; window.addEventListener("keydown", listen); return () => window.removeEventListener("keydown", listen); });
  if (done) return <section className="session-shell"><div className="session-head"><button className="text-button" onClick={close}><X size={17} /> ปิดเซสชัน</button><span>{queue.length}/{queue.length}</span></div><div className="completion"><span className="completion-mark"><Check size={25} /></span><span className="eyebrow">SESSION COMPLETE</span><h1>ทำได้ดีมาก</h1><p>คุณเพิ่งบันทึกความทรงจำใหม่ {queue.length} คำ ระบบจะเตรียมรอบทบทวนถัดไปให้ตามระดับที่คุณจำได้</p><button className="button-primary" onClick={close}>กลับไปบันทึกวันนี้ <ChevronRight size={17} /></button></div></section>;
  return <section className="session-shell"><div className="session-head"><button className="text-button" onClick={close}><X size={17} /> ปิดเซสชัน</button><span>คำที่ {index + 1} จาก {queue.length}</span></div><div className="session-progress"><i style={{ width: `${(index + 1) / queue.length * 100}%` }} /></div><article className="flashcard"><div className="card-top"><span>{current.pos || "vocabulary"}</span><span className="card-dots">{[1,2,3,4,5].map(n => <i key={n} className={n <= (store[keyOf(current)]?.repetitions || 0) ? "filled" : ""} />)}</span></div><div className="card-body"><p className="pronunciation">{current.ipa || "—"}</p><h1>{current.w}</h1>{revealed ? <div className="answer"><span>{current.th_ipa}</span><strong>{current.th}</strong><p>การนึกคำตอบก่อนดูเฉลย จะช่วยให้จำคำศัพท์ได้นานขึ้น</p></div> : <button className="reveal-button" onClick={() => setRevealed(true)}>แสดงคำแปล <span>Space</span></button>}</div></article>{revealed ? <div className="grade-grid">{(["again","hard","good","easy"] as Grade[]).map((value, i) => <button key={value} className={`grade ${value}`} onClick={() => grade(value)}><small>{i + 1}</small><strong>{gradeLabel(value)}</strong><span>{nextIntervalLabel(store[keyOf(current)], value)}</span></button>)}</div> : <p className="session-hint">นึกถึงคำแปลและคำอ่านก่อน แล้วกด Space เพื่อดูคำตอบ</p>}</section>;
}
function Today({ words, due, total, store, start, apiKey, onGameReview }: { words: VocabularyWord[]; due: VocabularyWord[]; total: number; store: SrsStore; start: (mode: "review" | "new") => void; apiKey: string; onGameReview: (word: VocabularyWord) => void }) {
  const [log, setLog] = useState<Record<string, number>>(() => readDailyLog());
  const fresh = words.slice(0, 4); const progress = Math.min(100, Math.round(total / Math.max(total + due.length, 8) * 100));
  const streak = useMemo(() => computeStreak(log), [log]);
  const goalPct = Math.min(100, Math.round((streak.todayCount / streak.goal) * 100));
  return <main className="content"><section className="page-intro"><div><span className="eyebrow">{thaiDate()}</span><h1>บันทึกการเรียน<br /><i>ของวันนี้</i></h1><p>คำที่กลับมาในเวลาที่เหมาะสม จะอยู่กับคุณได้นานกว่า</p><div className="date-stamp"><span>STUDY ENTRY</span><strong>16</strong><small>AUG · 2026</small></div></div><div className="hero-art" style={{ backgroundImage: `url(${asset.hero})` }}><span>สม่ำเสมอ<br />สำคัญกว่า<br />สมบูรณ์แบบ</span><i className="card-motif" /></div></section><section className="today-layout"><div className="review-panel"><span className="ledger-index">01 / REVIEW</span><div className="section-heading"><div><span className="eyebrow">DUE TODAY</span><h2>คำที่รอการทบทวน</h2></div><span className="due-number">{due.length}</span></div>{due.length ? <><p className="section-copy">ให้เวลากับคำเหล่านี้สักครู่ ระบบจะอัปเดตรอบถัดไปตามระดับที่คุณจำได้</p><button className="button-primary" onClick={() => start("review")}>เริ่มทบทวน {due.length} คำ <ChevronRight size={17} /></button></> : <div className="empty-slate"><img src={asset.garden} alt="สวนความจำ" /><div><span className="eyebrow">ROOM TO GROW</span><h2>วันนี้ไม่มีคำที่ต้องทบทวน</h2><p>เริ่มคำใหม่สั้น ๆ เพื่อให้ระบบจัดตารางครั้งต่อไปให้คุณ</p><button className="button-primary" onClick={() => start("new")}>เริ่มเรียนคำใหม่ <ArrowUpRight size={16} /></button></div></div>}</div><div className="ledger-stat"><div className="stat-card"><span className="eyebrow">TODAY'S RHYTHM</span><Ring value={progress} /><strong>{total} <small>รอบ</small></strong><p>รอบที่ทบทวนแล้ววันนี้</p></div><div className="streak-card"><Flame size={21} /><strong>{streak.currentStreak} วันติด</strong><span>สูงสุด {streak.bestStreak} วัน</span></div><div className="goal-card"><Target size={19} /><div className="goal-info"><strong>เป้าหมายวันนี้</strong><div className="goal-bar"><i style={{ width: `${goalPct}%` }} /><span className="goal-label">{streak.todayCount}/{streak.goal} รอบ</span></div></div><input type="number" min={1} max={100} className="goal-input" value={streak.goal} onChange={e => { const v = Number(e.target.value); if (v > 0) { setDailyGoal(v); setLog(readDailyLog()); } }} aria-label="กำหนดเป้าหมายรายวัน (รอบ)" /></div></div></section><DailyStarter words={words} store={store} onStart={() => start("new")} />
        <ListeningDrill words={words} apiKey={apiKey} />
        <ReviewGames words={words} onGameReview={onGameReview} />
        <ChatPractice apiKey={apiKey} /><section className="next-section"><div className="section-heading"><div><span className="eyebrow">START FRESH</span><h2>คำใหม่ที่น่าลองวันนี้</h2></div><button className="text-button" onClick={() => start("new")}>เรียนคำใหม่ <ChevronRight size={17} /></button></div><div className="word-strip">{fresh.map((word, i) => <article className="word-preview" key={word.w}><small>ENTRY<br />0{i + 1}</small><div><strong>{word.w}</strong><span>{word.th}</span></div><ArrowUpRight size={17} /></article>)}</div></section></main>;
}
function Library({ words, store, saved, setSaved, schedule }: { words: VocabularyWord[]; store: SrsStore; saved: string[]; setSaved: (next: string[]) => void; schedule: (word: VocabularyWord) => void }) {
  const [query, setQuery] = useState(""); const [pos, setPos] = useState("all"); const [letter, setLetter] = useState<string>("all"); const types = Array.from(new Set(words.map(w => w.pos).filter(Boolean))).slice(0, 7);
  const firstLetters = useMemo(() => Array.from(new Set(words.map(w => w.w[0]?.toUpperCase() || ""))).sort(), [words]);
  const list = useMemo(() => words.filter(w => (pos === "all" || w.pos === pos) && (letter === "all" || (w.w[0]?.toUpperCase() || "") === letter) && `${w.w} ${w.th} ${w.th_ipa}`.toLowerCase().includes(query.toLowerCase())).slice(0, 60), [words, pos, query, letter]);
  return <main className="content library-content"><section className="library-title"><span className="eyebrow">THE REFERENCE SHELF</span><h1>คลังคำศัพท์</h1><p>ค้นหาคำจากคลัง 5,000 คำ แล้วเพิ่มคำที่อยากจำเข้าสู่รอบทบทวนของคุณ</p></section><div className="search-box"><Search size={20} /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="ค้นหาคำศัพท์, คำอ่าน หรือคำแปลไทย" /><span>{words.length.toLocaleString()} คำ</span></div><div className="az-bar" role="tablist" aria-label="ตัวอักษร A–Z"><button className={letter === "all" ? "selected" : ""} onClick={() => setLetter("all")}>ALL</button>{Array.from({ length: 26 }, (_, i) => String.fromCharCode(65 + i)).map(ch => { const has = firstLetters.includes(ch); return <button key={ch} className={`${letter === ch ? "selected" : ""}${has ? "" : " unused"}`} disabled={!has} onClick={() => has && setLetter(ch)}>{ch}</button>; })}</div><div className="filter-row"><button className={pos === "all" ? "selected" : ""} onClick={() => setPos("all")}>ทั้งหมด</button>{types.map(type => <button className={pos === type ? "selected" : ""} onClick={() => setPos(type)} key={type}>{type}</button>)}</div><section className="word-table"><div className="table-meta"><span>ผลการค้นหา {list.length} คำ</span><span>บันทึกแล้ว {saved.length} คำ</span></div>{list.map(word => { const key = keyOf(word); const bookmarked = saved.includes(key); return <article className="table-word" key={key}><div className="word-main"><strong>{word.w}</strong><span>{word.ipa || "—"} · {word.pos || "word"}</span></div><div className="word-translation"><span>{word.th_ipa}</span><strong>{word.th}</strong></div><div className="word-actions"><button title="บันทึกคำนี้" className={bookmarked ? "saved" : ""} onClick={() => setSaved(bookmarked ? saved.filter(item => item !== key) : [...saved, key])}><BookOpen size={17} /></button><button className={store[key] ? "scheduled" : ""} onClick={() => schedule(word)}>{store[key] ? "อยู่ในแผน" : "เพิ่มทบทวน"}</button></div></article>; })}</section></main>;
}
function WeeklyStats() {
  const [log, setLog] = useState<Record<string, number>>(() => readDailyLog());
  const week = lastSevenDays(log); const max = Math.max(1, ...week.map(item => item.count)); const weekTotal = week.reduce((sum, item) => sum + item.count, 0);
  useEffect(() => { const refresh = setInterval(() => setLog(readDailyLog()), 3000); return () => clearInterval(refresh); }, []);
  return <section className="library-title" style={{ paddingTop: 26 }}><span className="eyebrow">LAST 7 DAYS</span><h1>เป้าหมายรายสัปดาห์</h1><p>แค่ทบทวนคำเดิมในหน้า "วันนี้" จำนวนรอบต่อวันจะถูกนับให้อัตโนมัติ — เป้าหมายสัปดาห์แรกคือครบ 7 วันติดกันให้ได้</p><div className="insight-metrics" style={{ marginTop: 18 }}><div><strong>{weekTotal}</strong><span>รอบทบทวน 7 วันนี้</span></div><div><strong>{week.filter(item => item.count > 0).length}/7</strong><span>วันที่ได้เรียน</span></div></div><div className="week-chart">{week.map(item => <div key={item.day} className={`week-col${item.day === week[6].day ? " today" : ""}`}><strong style={{ fontSize: 11 }}>{item.count}</strong><i className="week-bar" style={{ height: `${Math.max(3, Math.round(item.count / max * 92))}px` }} /><span>{item.short}</span></div>)}</div>{weekTotal === 0 ? <p className="week-empty">ยังไม่มีบันทึก — เริ่มทบทวนคำแรกแล้วกราฟจะเริ่มขึ้นเอง</p> : null}</section>;
}

function Insights({ store, words }: { store: SrsStore; words: VocabularyWord[] }) {
  const values = Object.values(store); const mature = values.filter(item => item.interval >= 21).length; const average = values.length ? (values.reduce((sum, item) => sum + item.easeFactor, 0) / values.length).toFixed(1) : "—";
  return <main className="content insights"><section className="library-title"><span className="eyebrow">YOUR MEMORY, OVER TIME</span><h1>ความคืบหน้า</h1><p>ระบบจะจัดคำศัพท์ตามจังหวะความจำของคุณ ไม่ใช่จำนวนวันที่ผ่านไป</p></section><WeeklyStats /><section className="insight-hero"><div><span className="eyebrow">MEMORY GARDEN</span><h2>ทุกครั้งที่คุณนึกออก<br />คือรากที่แข็งแรงขึ้น</h2><div className="insight-metrics"><div><strong>{values.length}</strong><span>คำที่เริ่มเรียน</span></div><div><strong>{mature}</strong><span>คำที่จำได้ระยะยาว</span></div><div><strong>{average}</strong><span>ค่าเฉลี่ยความง่าย</span></div></div></div><img src={asset.progress} alt="ภาพประกอบความก้าวหน้าการเรียน" /></section><section className="insight-grid"><article><Clock3 size={20} /><span className="eyebrow">PRIVATE BY DEFAULT</span><strong>Local</strong><p>ข้อมูลของคุณไม่ถูกส่งออกจากเครื่อง</p></article><article><Layers3 size={20} /><span className="eyebrow">FULL LIBRARY</span><strong>{words.length.toLocaleString()}</strong><p>คำศัพท์พร้อมให้คุณเริ่มเรียน</p></article><article><RotateCcw size={20} /><span className="eyebrow">HOW IT WORKS</span><strong>SM-2</strong><p>ยิ่งจำได้ง่าย รอบถัดไปยิ่งห่าง</p></article></section></main>;
}
export default function Home() {
  const { words, isLoading, error } = useVocabulary(); const [view, setView] = useState<View>("today"); const [store, setStore] = useState<SrsStore>(() => stored(STORE_KEY, {})); const [saved, setSaved] = useState<string[]>(() => stored(SAVED_KEY, [])); const [session, setSession] = useState<VocabularyWord[] | null>(null);
  const due = useMemo(() => words.filter(word => isDue(store[keyOf(word)])).sort((a,b) => new Date(store[keyOf(a)]?.dueAt || 0).getTime() - new Date(store[keyOf(b)]?.dueAt || 0).getTime()), [words, store]); const total = useMemo(() => Object.values(store).reduce((sum, item) => sum + item.totalReviews, 0), [store]);
  useEffect(() => localStorage.setItem(STORE_KEY, JSON.stringify(store)), [store]); useEffect(() => localStorage.setItem(SAVED_KEY, JSON.stringify(saved)), [saved]);
  const [apiKey] = useState<string>(() => localStorage.getItem("englishvocab-mistral-key-v1") || ""); const [level] = useState<"beginner" | "elementary" | "intermediate">(() => ((): "beginner" | "elementary" | "intermediate" => { const l = stored<{ level?: string }>("englishvocab-placement-v1", {}).level; return l === "intermediate" || l === "elementary" ? l : "beginner"; })());
  const start = (mode: "review" | "new") => { const fresh = words.filter(word => !store[keyOf(word)]); const queue = mode === "review" && due.length ? due.slice(0, 12) : fresh.slice(0, 12); if (!queue.length) return toast("คุณเรียนคำใหม่ครบแล้ว", { description: "เลือกคำจากคลังเพื่อเพิ่มเข้าสู่แผนการทบทวน" }); setSession(queue); };
  const schedule = (word: VocabularyWord) => { setStore(current => ({ ...current, [keyOf(word)]: current[keyOf(word)] || reviewWord(undefined, "again") })); toast("เพิ่มคำศัพท์เข้ารอบทบทวนแล้ว", { description: word.w }); };
  const onGameReview = (word: VocabularyWord) => { logTodayReview(); setStore(current => ({ ...current, [keyOf(word)]: reviewWord(current[keyOf(word)], "good") })); };
  if (isLoading) return <div className="loading-page"><img src={asset.logo} alt="" /><strong>กำลังเปิดสมุดบันทึกของคุณ...</strong><span>เตรียมคลังคำศัพท์ 5,000 คำ</span></div>;
  if (session) return <div className="app-shell session-mode"><Header onReview={() => start("review")} /><StudySession queue={session} store={store} onGrade={(word, grade) => { logTodayReview(); setStore(current => ({ ...current, [keyOf(word)]: reviewWord(current[keyOf(word)], grade) })); }} close={() => setSession(null)} /></div>;
  return <div className="app-shell"><Header onReview={() => start("review")} /><div className="app-frame"><Sidebar view={view} setView={setView} due={due.length} />{error && <div className="data-notice">{error}</div>}{view === "today" && <Today words={words} due={due} total={total} store={store} start={start} apiKey={apiKey} onGameReview={onGameReview} />}{view === "library" && <Library words={words} store={store} saved={saved} setSaved={setSaved} schedule={schedule} />}{view === "insights" && <Insights store={store} words={words} />}<div style={{ padding: "0 52px 70px", maxWidth: 1070 }}><div style={{ paddingBottom: 10 }}><LearningHub apiKey={apiKey} words={words} level={level} onAddWord={schedule} /><PlacementTest words={words} apiKey={apiKey} onStartWords={schedule} /></div><ScenarioLab words={words} apiKey={apiKey} level={level} /><SentenceGym words={words} apiKey={apiKey} /><AiTutor words={words} scheduled={Object.values(store).length} /></div></div></div>;
}
